---
title: "Tidytuesday 10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries.

```{r}
library(tidyverse)
library(mdthemes)
library(ggtext)
windowsFonts("Bahnschrift" = windowsFont("Bahnschrift"))
```

Load data.

```{r}
mobile <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/mobile.csv')
landline <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/landline.csv')
```

Join both datasets.

```{r}
data <- inner_join(mobile, select(landline, code, year, landline_subs), by = c("code", "year")) %>% 
            mutate(year = as.character(year),
                   continent = case_when(continent == "Africa" ~ "África",
                                         continent == "Americas" ~ "América",
                                         continent == "Europe" ~ "Europa",
                                         TRUE ~ continent
                                        ))
```

Visualize with ggplot2.

```{r}
plot <- data %>% 
  group_by(continent, year) %>% 
  summarise(mobile = mean(mobile_subs, na.rm = T),
            landline = mean(landline_subs, na.rm = T)) %>% 
  ggplot() +
    geom_line(aes(year, landline, group = continent), color = "red",  size = .8) +
    geom_line(aes(year, mobile, group = continent), color = "blue",  size = .8) +
    scale_x_discrete(breaks = seq(1990, 2017, 9)) +
    facet_wrap(~ continent, scales = "free_x") +
    xlab(NULL) +
    ylab(NULL) +
      labs(title = "<b>Numero de lineas <span style='color:red'>fijas</span> y <span style='color:blue'>moviles</span> por 100 habitantes (1990-2017)",
         subtitle = "El número de líneas móviles se dispara desde finales de los años 90 en todo el mundo",
         caption = "Fuente: Pew Research Smartphone Adoption | @jantleon") +
    theme_minimal(base_family = "Bahnschrift") +
    theme(legend.position = "none",
          plot.title = element_markdown(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          panel.spacing.x = unit(6, "mm"))

plot
```

Save the plot.

```{r}
ggsave("R/2020-11-10/plot.png", plot, width = 6, height = 4)
```

